services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - .env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:16.3-alpine3.20
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - .env